### ISSUE TITLE
More source

### ISSUE THREAD

**Issue by johnthad** [WebComponentsBook/x-dialog#1]
Maybe I'm jumping the gun, but I'm anxious to try some examples as I read along. I bought the EPUB version of _Developing Web Components_, so it's a fairly easy process to copy and paste the snippets and try them out in Chrome (now v41.x; I'm running Apache on my Mac, so the pages are being loaded from http vs. file).

I used this copy-paste routine with Chapter 11 and the examples worked okay. I think I see what's going on. In Chapter 12, I've tried to load the snippet in "Resolving Custom Elements" and print results to the console. This is what I crafted

```
<html>
  <head>
  </head>
  <body>
    <jason-is-awesome>Let me count the ways.</jason-is-awesome>
    <script type="text/javascript">
      var jasonIsAwesomeEl = document.querySelector('jason-is-awesome');
      // isUnknown is true
      var isUnknown = jasonIsAwesomeEl.__proto__ === HTMLUnknownElement
          .prototype;
      console.log("jasonIsAwesomeEl isUnknown before register: " + isUnknown);

      document.registerElement('jason-is-awesome');
      // isUnknown is false
      isUnknown = jasonIsAwesomeEl.__proto__ === HTMLUnknownElement.prototype;
      console.log("jasonIsAwesomeEl isUnknown after register: " + isUnknown);

      // continuing from the last example...
      // isHTMLElement is true
      var isHTMLElement = jasonIsAwesomeEl.__proto__ === HTMLElement.prototype;
      console.log("jasonIsAwesomeEl isHTMLElement: " + isHTMLElement);
    </script>
  </body>
</html>
```

From the comments--which you see I copied--I expected `true`, `false`, `true` in the console, but get all `false`. What's happening? Is my page missing something? I understand that web components are bleeding edge. Has something changed in Chrome since the example was written?

(I knew before I bought the book that Polymer was moving soon from 0.5.5 to 0.8, and that Google had warned there would be breaking changes. Still I bought the book because I'm anxious to jump on this. In this job, you gotta expect to bleed a little.)

**Comment by jstrimpel** [comment]
Looks like the W3C spec has changed since publication, http://www.w3.org/TR/custom-elements/#registering-custom-elements:

"the unresolved element's element interface must be... the HTMLElement, if the namespace is HTML Namespace;"

**Comment by jstrimpel** [comment]
Latest draft from github, http://w3c.github.io/webcomponents/spec/custom/#registering-custom-elements.

**Comment by johnthad** [comment]
Thanks. Ah the joys of the bleeding edge. You're probably gonna have a large errata page. :)
